### ISSUE TITLE
Your opinion on a spelling question

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#20]
Hi Alexis,

In the orthography, we don't like words being too long, even for compounds. For instance, 'kelp' is "aebbae chaehree" ('goiter medicine'). However, if the meanings of the input words are no longer transparent, we have no choice but to join them together into one word. I've been looking at all the "mushroom" compounds, which are unusually long words in the orthography:

- 

- æ̃˩ʂe˧li˥-mo˩ /æ̃˩ʂe˧li˥mo˩/ aensheilimo
- - æ̃˧tsɯ˥-kʰɯ˩ʈʂɤ˩-mo˩ /æ̃˧tsɯ˥-kʰɯ˩ʈʂɤ˩mo˩/ aenzi keezhe mo
- - dzi˧dzi˧-mo˧˥ /dzi˧dzi˧mo˧˥/ zzeezzeemo

- ə˩ljɤ˩hæ̃˩ʂɯ˥-mo˩ /ə˩ljɤ˩hæ̃˩ʂɯ˥mo˩/ eliahaenshimo
- jɤ˧qʰɑ˧-pɤ˥jɤ˩-mo˩ /jɤ˧qʰɑ˧pɤ˥jɤ˩mo˩/ yekhabeyemo

As you can see, only 'chicken foot mushroom' is written as three separate words. For the sake of consistency, I think we need to either make this one word, or else to at least make "yekhabeye mo" two words. Not sure about the others. Any thoughts? Or maybe I should be discussing this with Siggeema and/or Ms. He. ;-)

**Comment by DuMeigui** [comment]
Alexis, I discussed this with Siggeema. She suggests:
aensheili mo
aenzi keezhe mo
zzeezzee mo
eliahaenshi mo
yekhabeye mo

**Comment by alexis-michaud** [comment]
'Mushroom' _mo_ as 1 unit, and the determiner as 1 or 2, depending on how 'analyzable' it feels: this makes good sense to me! 
Since the basis for the decision to split or not (_aenzi keezhe_ vs _aenzikeezhe_) is the perceived degree of independence, it is to be expected that different speakers will have different perceptions, and hence different ways of writing the words. It should be OK, and 'purists' who wish to go by the general consensus rather than by their own intuition can always look up the way a word is spelt in the dictionary.

I changed these entries in the lexical database (_aenzi keezhe mo_ was already 'split').
