### ISSUE TITLE
[Orthographic version of dictionary] Alphabetical order

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#27]
I would be extremely happy if the dictionary was eventually ordered according to Narua alphabetical order, not according to English/IPA alphabetical order. Just sayin'.

R

**Comment by alexis-michaud** [comment]
This is part of a broader project: to create an orthography-centered version of the dictionary. I have created a project grouping issues that seem relevant. Suggestions on the to-do list and how it should be prioritized are welcome. For want of available engineering / computer-science colleagues to do the work, no time line can be set for now.

**Comment by DuMeigui** [comment]
I have already given you a list of Narua alphabetical order, right?

**Comment by alexis-michaud** [comment]
It would be great to repeat it here for the record. For your reference, I repeat below the current (International Phonetic Alphabet-based) sort order.

The dictionary uses a three-level sort procedure: the vowels & consonants, then the tone marks & marks for tonal subcategories, and finally the homonym numbers (figures). 

There are a couple doublets, such as `[ṽ̩, ṽ̩]` so that the script treats the `ṽ̩` in the same way whether the nasalization diacritic comes before or after the syllabic diacritic and treats `ɻ` and `ɻ̍` the same way (=for cases where the user forgot the syllabic diacritic). 

```
  ordre lexicographique: 
      - [ɑ, ɑ̃, æ, æ̃, b, ɕ, d, dz, dʑ, ɖ, ɖʐ, e, ɤ, ɤ̃, ə, f, g, ɣ, h, i, ĩ, j, jæ, jɤ, je, jo, ʝ, k, kʰ, l, ɭ, ɬ, m, n, ɳ, ɲ, ŋ, o, õ, p, pʰ, q, qʰ, ɻ, ɻ̍, ɻ ̍̃, ʁ, s, ʂ, t, tʰ, tɕ, tɕʰ, ts, tsʰ, ʈ, ʈʰ, ʈʂ, ʈʂʰ, u, ɯ, v, [ṽ̩, ṽ̩], w, wɑ, wæ, wɤ, wo, wɤ̃, w̃, w̃æ, z, ʐ, ʑ, x]
      - [˥, ˧, ˩, α, β, γ, "$", "#"]
      - chiffres
```

**Comment by DuMeigui** [comment]
Initials: b, bb, c, ch, d, dd, f, g, gg, gh, h, hr, j, jj, k, kh, l, lh, m, n, ng, ny, p, q, r, s, ss, sh, t, v, w, x, xx, y, z, zz, zh, zzh

Finals: a, an, ae, aen, e, ee, ei, eo, er, eu, eun, i, in, ia, ian, ie, o, on, u, un, ua, uan, uae, uaen, uo

Word-final q does not affect alphabetical order.
The presence of an apostrophe indicates a syllable boundary.

**Comment by alexis-michaud** [comment]
Looking at the list, the order is clearly different from an alphabetic ordering of the International Phonetic Alphabet letters, as bb and b are not next to each other. Clearly, the IPA order is pretty remote from the internal logic of Narua phonology. 
It will be for an orthography-centered version of the dictionary to adopt this order.

**Comment by alexis-michaud** [comment]
"It will be for an orthography-centered version of the dictionary to adopt this order."
