### ISSUE TITLE
Add dialect tags to dictionary entries

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#32]
Re this item:
jɤ˧wo˧˥
\or ye'uo
\de To regress.
\ge to_regress
\dn 倒退、退步
\gn 倒退

SGM says:  我们说的事le'uo
那个发音是舌头有问题的人发的

**Comment by alexis-michaud** [comment]
Fourteen years ago I got a similar comment about my Naxi main consultant (He Xixian, M4: same number as Ama, F4! It seems for me the saying should be 'fourth time lucky' not 'third time lucky'!) from a colleague who had studied Naxi in another area: to him, it seemed that the speaker had some kind of slur or speech defect. In fact it was a case of difference between dialects. Fortunately that colleague finally agreed with me instead of doubting the quality of the data.

_le'uo_ and _ye'uo_ are distinct items in F4's speech.

You'll hear more such comments as you go through more items. Speakers of Laze consider that their language is the correct, 'pure' one and Naxi, Na/Narua... are 'corrupt', etc. It's a natural thought, coming from someone who knows a complete system that works just fine (her own native speech) and comes across piecemeal information about a clearly similar but puzzlingly non-identical speech variety. 

One possible way forward would be to add a dialect (or speaker) tag every time you discuss an item with a speaker. All items currently in the dictionary would be tagged as 'Alawua' to start with; additional tags would be used for other dialects. For instance, a tag SGM="yes" could be added to ye'uo, and a SGM="yes" to words that she agrees with. A three-way scale could even be used: YES = "perfect fit with her dialect", IFFY "understandable though there is some disagreement on form or meaning", or NO = "unintelligible: looks like a mistake".

Currently, variants for speakers other than F4 are coded thus in the Toolbox file:
```
\va <speaker="F5"> ID.
\va <speaker="M21"> lʰæ˧˥
\va <speaker="M23"> ID.
```

where `ID.` means 'identical' (i.e. the item was checked, and elicitation yielded the same result as for F4) and any other content is that speaker's pronunciation. Then we'd need speaker codes for your collaborators & friends. (SGM is F15, Ddeema is F17, La Mingqing is M31.)

After iteration of this process with speakers from various areas, it would be possible to calculate a "consensus index": finding out which forms are most widespread in which areas. This could be shown on a map (a "heat map" of the Narua area) for each item, showing its geographical extension. It could serve to make decisions such as tagging a word as "Common" in the dictionary, as Tom Pinson did for Naxi: he uses a "Common" tag to refer to forms that in his experience are common to all Western Naxi dialects. Thus, part of the dictionary would be tagged (flagged?) as uncontroversial (at least less controversial) and more suitable for use in an orthography primer, for instance. 

May I change this Issue's title to "Add dialect tags to dictionary entries"?

**Comment by DuMeigui** [comment]
Yes! I can think of a lot of uses for dialect tags!

R :-)

On 12 Jun 2018 00:07, Alexis Michaud <notifications@github.com> wrote:

Fourteen years ago I got a similar comment about my Naxi main consultant (He Xixian, M4: same number as Ama, F4! It seems for me the saying should be 'fourth time lucky' not 'third time lucky'!) from a colleague who had studied Naxi in another area: to him, it seemed that the speaker had some kind of slur or speech defect. In fact it was a case of difference between dialects. Fortunately that colleague finally agreed with me instead of doubting the quality of the data.

le'uo and ye'uo are distinct items in F4's speech.

You'll hear more such comments as you go through more items. Speakers of Laze consider that their language is the correct, 'pure' one and Naxi, Na/Narua... are 'corrupt', etc. It's a natural thought, coming from someone who knows a complete system that works just fine (her own native speech) and comes across piecemeal information about a clearly similar but puzzlingly non-identical speech variety.

One possible way forward would be to add a dialect (or speaker) tag every time you discuss an item with a speaker. All items currently in the dictionary would be tagged as 'Alawua' to start with; additional tags would be used for other dialects. For instance, a tag SGM="yes" could be added to ye'uo, and a SGM="yes" to words that she agrees with. A three-way scale could even be used: YES = "perfect fit with her dialect", IFFY "understandable though there is some disagreement on form or meaning", or NO = "unintelligible: looks like a mistake".

Currently, variants for speakers other than F4 are coded thus in the Toolbox file:

\va <speaker="F5"> ID.
\va <speaker="M21"> lʰæ˧˥
\va <speaker="M23"> ID.


where ID. means 'identical' (i.e. the item was checked, and elicitation yielded the same result as for F4) and any other content is that speaker's pronunciation. Then we'd need speaker codes for your collaborators & friends. (SGM is F15, Ddeema is F17, La Mingqing is M31.)

After iteration of this process with speakers from various areas, it would be possible to calculate a "consensus index": finding out which forms are most widespread in which areas. This could be shown on a map (a "heat map" of the Narua area) for each item, showing its geographical extension. It could serve to make decisions such as tagging a word as "Common" in the dictionary, as Tom Pinson did for Naxi: he uses a "Common" tag to refer to forms that in his experience are common to all Western Naxi dialects. Thus, part of the dictionary would be tagged (flagged?) as uncontroversial (at least less controversial) and more suitable for use in an orthography primer, for instance.

May I change this Issue's title to "Add dialect tags to dictionary entries"?

**Comment by alexis-michaud** [comment]
Then please go ahead.

In the \va (variant) field, what do you suggest?

| contents of field              | meaning                                                |   
|------------------|---------------------------------------------------------------|
| ID.              | identical form                                                  |
| NO               | unintelligible: looks like a mistake to the consultant         |
| IFFY             | vaguely intelligible but with potential for misunderstanding   |
| alternative form | the consultant uses another word: provide it in full (in IPA) | 

The speaker code needs to be indicated inside the tag `<speaker="XX">`. Available codes start at F20 and M39.

If you would like me to put a hold on editing the Toolbox file (master file: na.lex) at my end, let me know. Then you can download it from this repository & edit it at leisure, including the additional speaker tags.

**Comment by DuMeigui** [comment]
Hey, Alexis,


I'm currently in LJ and will not be able to go anywhere near the dictionary - except as reference material - for at least another couple of weeks. So please keep on editing to your heart's content!


BTW, as I suspected, I do know the people in that wee restaurant that you told me about here. They're still talking about you, hehe.


Blessings to you and yours,

Roselle 🌹


________________________________

**Comment by alexis-michaud** [comment]
Closing the issue for now: the choice made consists in providing speaker information, all from one dialect. A multi-dialect dictionary is a thorny project, as **anything can vary** between 2 dialects.
