### ISSUE TITLE
Schwa

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#40]
Alexis, I'm back onto the orthography paper  ("At last!", I can hear you say), and of course am often referring to your dictionary. I've been looking at schwa, and a couple of things have come up.

1. In your current analysis, schwa only appears as a syllable on its own. (I like that!) However, there are two places in the dictionary where it still appears in the ACCOMP prefix (transcribed elsewhere as /le/) and needs to be edited, i.e.:

- tɕi˩-hĩ˩ l**ə**˥-mɤ˩-mæ˩! (in mæ˧ ₂)

- ¶ l**ə**-˧wo˧ tʰo˥-tɕo˩ (in wo˧˥) 

2. I wonder why you've changed the transcription of the ACCOMP prefix, previously /lə/, to /le/ and not to /lɤ/, as per the NEG prefix /mɤ/.  The transcription /le/ suggests the spelling _lei_. It also mucks up one of my tables, hehe.

**Comment by alexis-michaud** [comment]
Point (1): thanks for pointing those out! I failed to spot the first because of the mis-inputting: lə-˧ (should have been lə˧- in the first place). No excuse for failing to spot the second: this points to a weak spot in the manual search-replace tasks I do straight on the source file with Notepad++.

Point (2): 

> I wonder why you've changed the transcription of the ACCOMP prefix, previously /lə/, to /le/ and not to /lɤ/, as per the NEG prefix /mɤ/. The transcription /le/ suggests the spelling lei. 

The vowel does not sound the same to me as that of the negation (in the same contexts: before the same verbs). I don't think that the reason why I was drawn to /le˧-/ is because that is the exact form this morpheme has in Naxi
