### ISSUE TITLE
Tugho

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#51]
Hi Alexis,

These three items could have a spelling change in the dictionary:
dɤ˩-tʰv̩˧qo˧ ('way over there'): currently _ddeq teegho_, change to _ddeq **tugho**_
gɤ˩-tʰv̩˧qo˧ ('way up there'): currently _ggeq teegho_, change to _ggeq **tugho**_
tʰv̩˧qo˧ ('there, that place'): currently _teegho_, change to _**tugho**_

Even though each of these has a corresponding _**teegho**_ form, I think we can include these as alternative spellings. Do you agree?

R

**Comment by alexis-michaud** [comment]
Yes, it's good to distinguish the proximal and distal forms in the dictionary. Since there is a straightforward way to represent the two forms in the orthography, it seems best to have different forms: 

```
\lx dɤ˩-tʰv̩˧qo˧
\or ddeq tugho
```

vs.

```
\lx dɤ˩-ʈʂʰɯ˧qo˧
\or ddeq teegho
```

As for description as alternative spellings, it would place the information down in a field of the only entry for the distal forms, which would not be too good for users who want to look up a word by browsing through the dictionary. Instead, it seems best to have separate entries, and to link them to one another through the `\cf` field.

```
\lx dɤ˩-ʈʂʰɯ˧qo˧
(...)
\cf dɤ˩-tʰv̩˧qo˧

\lx dɤ˩-tʰv̩˧qo˧
(...)
\cf dɤ˩-ʈʂʰɯ˧qo˧
```

**Comment by alexis-michaud** [comment]
Done, also changing this one:

```
\lx gɤ˩-tʰv̩˧-gi#˥
\or ggeq tuggi
```
