### ISSUE TITLE
English gloss in a dictionary item

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#55]
Dictionary item: \lx ho˧ɕjæ˩
\ge currently: cord_to_which_fire_is_put
\de currently: Cord to which fire is put in order to shoot.

Suggest change to:
\ge fuse  (Or possibly fuse cord)
\de Fuse for lighting gunpowder, fireworks etc. (Is this accurate? I'm guessing the context here.)

**Comment by alexis-michaud** [comment]
```
\lx ho˧ɕjæ˩
\sf <nb="B"> 618
\sf <nb="2011"> 911
\or hoxae
\bw <langue="cmn"> 火线
\ps n
\lc ho˧ɕjæ˩
\de Cord to which fire is put in order to shoot.
\ge 火线::cord_to_which_fire_is_put
\dn 火绳，导火索
\gn 导火索
\gr 火线
\df Mèche.
\gf 火线::mèche
```
![image](https://user-images.githubusercontent.com/6072524/86505809-7f4c3b80-bdc9-11ea-82e7-43b3edfd8bc2.png)

I had a misconception that flintlock guns operated in the same way as bombs or firecrackers, with a cord (fuse) that burns until it reaches the gunpowder. On checking, I realize that this is not the case: when shooting with an arquebus and the like, the fuse was not *on* the gun itself, but held in the hand and brought in contact with the gunpowder in order to shoot. 

I guess the term would apply for fireworks (firecrackers). I did not ask. 

So in English, 'wick' is for a candle, and ['fuse' for guns / explosives](https://en.wikipedia.org/wiki/Fuse_(explosives))! Thanks for pointing this out! I did not know this use of the word 'fuse', only the contemporary term in electricity (interestingly, the technique of electric fuses is derived from the older technique). Good to know. 

Here we go:
\ge fuse_cord
\de Fuse cord for lighting gunpowder, fireworks etc.
